Item.createItem("item_axe_crystal_black", "axe crystal black", {name: "item_axe_crystal_black", meta: 0}, {stack: 64});
Item.createItem("item_axe_crystal_blue", "axe crystal blue", {name: "item_axe_crystal_blue", meta: 0}, {stack: 64});
Item.createItem("item_axe_crystal_green", "axe crystal green", {name: "item_axe_crystal_green", meta: 0}, {stack: 64});
Item.createItem("item_axe_crystal_light_blue", "axe crystal light blue", {name: "item_axe_crystal_light_blue", meta: 0}, {stack: 64});
Item.createItem("item_axe_crystal_red", "axe crystal red", {name: "item_axe_crystal_red", meta: 0}, {stack: 64});
Item.createItem("item_axe_crystal_white", "axe crystal white", {name: "item_axe_crystal_white", meta: 0}, {stack: 64});
Item.createItem("item_axe_emerald", "axe emerald", {name: "item_axe_emerald", meta: 0}, {stack: 64});
Item.createItem("item_axe_light", "axe light", {name: "item_axe_light", meta: 0}, {stack: 64});
Item.createItem("item_axe_obsidian", "axe obsidian", {name: "item_axe_obsidian", meta: 0}, {stack: 64});
Item.createItem("item_axe_quartz", "axe quartz", {name: "item_axe_quartz", meta: 0}, {stack: 64});
Item.createItem("item_bag", "bag", {name: "item_bag", meta: 0}, {stack: 64});
Item.createItem("item_battery_double", "battery double", {name: "item_battery_double", meta: 0}, {stack: 64});
Item.createItem("item_battery_quadruple", "battery quadruple", {name: "item_battery_quadruple", meta: 0}, {stack: 64});
Item.createItem("item_battery_quintuple", "battery quintuple", {name: "item_battery_quintuple", meta: 0}, {stack: 64});
Item.createItem("item_battery_triple", "battery triple", {name: "item_battery_triple", meta: 0}, {stack: 64});
Item.createItem("item_battery", "battery", {name: "item_battery", meta: 0}, {stack: 64});
Item.createItem("item_booklet", "booklet", {name: "item_booklet", meta: 0}, {stack: 64});
Item.createItem("item_bucket_canola_oil", "bucket canola oil", {name: "item_bucket_canola_oil", meta: 0}, {stack: 64});
Item.createItem("item_bucket_oil", "bucket oil", {name: "item_bucket_oil", meta: 0}, {stack: 64});
Item.createItem("item_chest_to_crate_upgrade", "chest to crate upgrade", {name: "item_chest_to_crate_upgrade", meta: 0}, {stack: 64});
Item.createItem("item_coffee_beans", "coffee beans", {name: "item_coffee_beans", meta: 0}, {stack: 64});
Item.createItem("item_coffee_seed", "coffee seed", {name: "item_coffee_seed", meta: 0}, {stack: 64});
Item.createItem("item_coffee", "coffee", {name: "item_coffee", meta: 0}, {stack: 64});
Item.createItem("item_color_lens", "color lens", {name: "item_color_lens", meta: 0}, {stack: 64});
Item.createItem("item_crafter_on_a_stick", "crafter on a stick", {name: "item_crafter_on_a_stick", meta: 0}, {stack: 64});
Item.createItem("item_crate_keeper", "crate keeper", {name: "item_crate_keeper", meta: 0}, {stack: 646});
Item.createItem("item_crate_to_crafty_upgrade", "crate to crafty upgrade", {name: "item_crate_to_crafty_upgrade", meta: 0}, {stack: 64});
Item.createItem("item_crystal_green", "crystal green", {name: "item_crystal_green", meta: 0}, {stack: 64});
Item.createItem("item_crystal_light_blue", "crystal light blue", {name: "item_crystal_light_blue", meta: 0}, {stack: 64});
Item.createItem("item_crystal_red", "crystal red", {name: "item_crystal_red", meta: 0}, {stack: 64});
Item.createItem("item_crystal_shard", "crystal shard", {name: "item_crystal_shard", meta: 0}, {stack: 64});
Item.createItem("item_crystal_white", "crystal white", {name: "item_crystal_white", meta: 0}, {stack: 64});
Item.createItem("item_damage_lens", "damage lens", {name: "item_damage_lens", meta: 0}, {stack: 64});
Item.createItem("item_disenchanting_lens", "disenchanting lens", {name: "item_disenchanting_lens", meta: 0}, {stack: 64});
Item.createItem("item_drill_black", "drill black", {name: "item_drill_black", meta: 0}, {stack: 64});
Item.createItem("item_drill_blue", "drill blue", {name: "item_drill_blue", meta: 0}, {stack: 64});
Item.createItem("item_drill_brown", "drill brown", {name: "item_drill_brown", meta: 0}, {stack: 64});
Item.createItem("item_drill_cyan", "drill cyan", {name: "item_drill_cyan", meta: 0}, {stack: 64});
Item.createItem("item_drill_gray", "drill gray", {name: "item_drill_gray", meta: 0}, {stack: 64});
Item.createItem("item_drill_green", "drill green", {name: "item_drill_green", meta: 0}, {stack: 64});
Item.createItem("item_drill_light_blue", "drill light blue", {name: "item_drill_light_blue", meta: 0}, {stack: 64});
Item.createItem("item_drill_light_gray", "drill light gray", {name: "item_drill_light_gray", meta: 0}, {stack: 64});
Item.createItem("item_drill_lime", "drill lime", {name: "item_drill_lime", meta: 0}, {stack: 64});
Item.createItem("item_drill_magenta", "drill magenta", {name: "item_drill_magenta", meta: 0}, {stack: 64});
Item.createItem("item_drill_orange", "drill orange", {name: "item_drill_orange", meta: 0}, {stack: 64});
Item.createItem("item_drill_pink", "drill pink", {name: "item_drill_pink", meta: 0}, {stack: 64});
Item.createItem("item_drill_purple", "drill purple", {name: "item_drill_purple", meta: 0}, {stack: 64});
Item.createItem("item_drill_red", "drill red", {name: "item_drill_red", meta: 0}, {stack: 64});
Item.createItem("item_drill_upgrade_block_placing", "upgrade block placing", {name: "item_drill_upgrade_block_placing", meta: 0}, {stack: 64});
Item.createItem("item_drill_upgrade_five_by_five", "upgrade five by five", {name: "item_drill_upgrade_five_by_five", meta: 0}, {stack: 64});
Item.createItem("item_drill_upgrade_fortune", "upgrade fortune", {name: "item_drill_upgrade_fortune", meta: 0}, {stack: 64});
Item.createItem("item_drill_upgrade_silk_touch", "upgrade silk touch", {name: "item_drill_upgrade_silk_touch", meta: 0}, {stack: 64});
Item.createItem("item_drill_upgrade_speed_ii", "upgrade speedIi", {name: "item_drill_upgrade_speed_ii", meta: 0}, {stack: 64});
Item.createItem("item_drill_upgrade_speed_iii", "upgrade speedIii", {name: "item_drill_upgrade_speed_iii", meta: 0}, {stack: 64});
Item.createItem("item_drill_upgrade_speed", "upgrade speed", {name: "item_drill_upgrade_speed", meta: 0}, {stack: 64});
Item.createItem("item_drill_upgrade_three_by_three", "upgrade three by three", {name: "item_drill_upgrade_three_by_three", meta: 0}, {stack: 64});
Item.createItem("item_drill_upgrade", "upgrade", {name: "item_drill_upgrade", meta: 0}, {stack: 64});
Item.createItem("item_drill_white", "drill white", {name: "item_drill_white", meta: 0}, {stack: 64});
Item.createItem("item_drill_yellow", "drill yellow", {name: "item_drill_yellow", meta: 0}, {stack: 64});
Item.createItem("item_dust", "dust", {name: "item_dust", meta: 0}, {stack: 64});
Item.createItem("item_engineer_goggles_advanced", "engineer goggles advanced", {name: "item_engineer_goggles_advanced", meta: 0}, {stack: 64});
Item.createItem("item_engineer_goggles", "engineer goggles", {name: "item_engineer_goggles", meta: 0}, {stack: 64});
Item.createItem("item_explosion_lens", "explosion lens", {name: "item_explosion_lens", meta: 0}, {stack: 64});
Item.createItem("item_fertilizer", "fertilizer", {name: "item_fertilizer", meta: 0}, {stack: 64});
Item.createItem("item_filling_wand", "filling wand", {name: "item_filling_wand", meta: 0}, {stack: 64});
Item.createItem("item_filter", "filter", {name: "item_filter", meta: 0}, {stack: 64});
Item.createItem("item_flax_seed", "flax seed", {name: "item_flax_seed", meta: 0}, {stack: 64});
Item.createItem("item_food_bacon", "food bacon", {name: "item_food_bacon", meta: 0}, {stack: 64});
Item.createItem("item_food_baguette", "food baguette", {name: "item_food_baguette", meta: 0}, {stack: 64});
Item.createItem("item_food_big_cookie", "food big cookie", {name: "item_food_big_cookie", meta: 0}, {stack: 64});
Item.createItem("item_food_cheese", "food cheese", {name: "item_food_cheese", meta: 0}, {stack: 64});
Item.createItem("item_food_chocolate_cake", "food chocolate cake", {name: "item_food_chocolate_cake", meta: 0}, {stack: 64});
Item.createItem("item_food_chocolate_toast", "food chocolate toast", {name: "item_food_chocolate_toast", meta: 0}, {stack: 64});
Item.createItem("item_food_chocolate", "food chocolate", {name: "item_food_chocolate", meta: 0}, {stack: 64});
Item.createItem("item_food_doughnut", "food doughnut", {name: "item_food_doughnut", meta: 0}, {stack: 64});
Item.createItem("item_food_fish_n_chips", "food fish n chips", {name: "item_food_fish_n_chips", meta: 0}, {stack: 64});
Item.createItem("item_food_french_fries", "food french fries", {name: "item_food_french_fries", meta: 0}, {stack: 64});
Item.createItem("item_food_french_fry", "food french fry", {name: "item_food_french_fry", meta: 0}, {stack: 64});
Item.createItem("item_food_hamburger", "food hamburger", {name: "item_food_hamburger", meta: 0}, {stack: 64});
Item.createItem("item_food_noodle", "food noodle", {name: "item_food_noodle", meta: 0}, {stack: 64});
Item.createItem("item_food_pizza", "food pizza", {name: "item_food_pizza", meta: 0}, {stack: 64});
Item.createItem("item_food_pumpkin_stew", "food pumpkin stew", {name: "item_food_pumpkin_stew", meta: 0}, {stack: 64});
Item.createItem("item_food_rice_bread", "food rice bread", {name: "item_food_rice_bread", meta: 0}, {stack: 64});
Item.createItem("item_food_rice", "food rice", {name: "item_food_rice", meta: 0}, {stack: 64});
Item.createItem("item_food_spaghetti", "food spaghetti", {name: "item_food_spaghetti", meta: 0}, {stack: 64});
Item.createItem("item_food_submarine_sandwich", "food submarine sandwich", {name: "item_food_submarine_sandwich", meta: 0}, {stack: 64});
Item.createItem("item_food_toast", "food toast", {name: "item_food_toast", meta: 0}, {stack: 64});
Item.createItem("item_growth_ring", "growth ring", {name: "item_growth_ring", meta: 0}, {stack: 64});
Item.createItem("item_hairy_ball", "hairy ball", {name: "item_hairy_ball", meta: 0}, {stack: 64});
Item.createItem("item_hoe_crystal_black", "hoe crystal black", {name: "item_hoe_crystal_black", meta: 0}, {stack: 64});
Item.createItem("item_hoe_crystal_blue", "hoe crystal blue", {name: "item_hoe_crystal_blue", meta: 0}, {stack: 64});
Item.createItem("item_hoe_crystal_green", "hoe crystal green", {name: "item_hoe_crystal_green", meta: 0}, {stack: 64});
Item.createItem("item_hoe_crystal_light_blue", "hoe crystal light blue", {name: "item_hoe_crystal_light_blue", meta: 0}, {stack: 64});
Item.createItem("item_hoe_crystal_red", "hoe crystal red", {name: "item_hoe_crystal_red", meta: 0}, {stack: 64});
Item.createItem("item_hoe_crystal_white", "hoe crystal white", {name: "item_hoe_crystal_white", meta: 0}, {stack: 64});
Item.createItem("item_hoe_emerald", "hoe emerald", {name: "item_hoe_emerald", meta: 0}, {stack: 64});
Item.createItem("item_hoe_crystal_light", "hoe crystal light", {name: "item_hoe_crystal_light", meta: 0}, {stack: 64});
Item.createItem("item_hoe_obsidian", "hoe obsidian", {name: "item_hoe_obsidian", meta: 0}, {stack: 64});
Item.createItem("item_hoe_quartz", "hoe quartz", {name: "item_hoe_quartz", meta: 0}, {stack: 64});
Item.createItem("item_jam_overlay", "jam overlay", {name: "item_jam_overlay", meta: 0}, {stack: 64});
Item.createItem("item_jam", "jam", {name: "item_jam", meta: 0}, {stack: 64});
Item.createItem("item_juicer", "juicer", {name: "item_juicer", meta: 0}, {stack: 64});
Item.createItem("item_knife", "knife", {name: "item_knife", meta: 0}, {stack: 64});
Item.createItem("item_laser_upgrade_invisibility", "laser upgradeInvisibility", {name: "item_laser_upgrade_invisibility", meta: 0}, {stack: 64});
Item.createItem("item_laser_upgrade_range", "laser upgrade range", {name: "item_laser_upgrade_range", meta: 0}, {stack: 64});
Item.createItem("item_laser_wrench", "laser wrench", {name: "item_laser_wrench", meta: 0}, {stack: 64});
Item.createItem("item_leaf_blower_advanced", "leaf blower advanced", {name: "item_leaf_blower_advanced", meta: 0}, {stack: 64});
Item.createItem("item_leaf_blower_advanced", "leaf blower advanced", {name: "item_leaf_blower_advanced", meta: 0}, {stack: 64});
Item.createItem("item_light_wand", "light wand", {name: "item_light_wand", meta: 0}, {stack: 64});
Item.createItem("item_manual", "manual", {name: "item_manual", meta: 0}, {stack: 64});
Item.createItem("item_medium_to_large_crate_upgrade", "medium to large crate upgrade", {name: "item_medium_to_large_crate_upgrade", meta: 0}, {stack: 64});
Item.createItem("item_minecart_firework_box", "minecart firework box", {name: "item_minecart_firework_box", meta: 0}, {stack: 64});
Item.createItem("item_mining_lens", "mining lens", {name: "item_mining_lens", meta: 0}, {stack: 64});
Item.createItem("item_misc_bat_wing", "bat wing", {name: "item_misc_bat_wing", meta: 0}, {stack: 64});
Item.createItem("item_misc_biocoal", "biocoal", {name: "item_misc_biocoal", meta: 0}, {stack: 64});
Item.createItem("item_misc_biomass", "biomass", {name: "item_misc_biomass", meta: 0}, {stack: 64});
Item.createItem("item_misc_black_dye", "black dye", {name: "item_misc_black_dye", meta: 0}, {stack: 64});
Item.createItem("item_misc_black_quartz", "black quartz", {name: "item_misc_black_quartz", meta: 0}, {stack: 64});
Item.createItem("item_misc_canola", "canola", {name: "item_misc_canola", meta: 0}, {stack: 64});
Item.createItem("item_misc_coil_advanced", "coil advanced", {name: "item_misc_coil_advanced", meta: 0}, {stack: 64});
Item.createItem("item_misc_coil", "coil", {name: "item_misc_coil", meta: 0}, {stack: 64});
Item.createItem("item_misc_crystallized_canola_seed", "crystallized canola seed", {name: "item_misc_crystallized_canola_seed", meta: 0}, {stack: 64});
Item.createItem("item_misc_cup", "cup", {name: "item_misc_cup", meta: 0}, {stack: 64});
Item.createItem("item_misc_dough", "dough", {name: "item_misc_dough", meta: 0}, {stack: 64});
Item.createItem("item_misc_drill_core", "drill core", {name: "item_misc_drill_core", meta: 0}, {stack: 64});
Item.createItem("item_misc_empowered_canola_seed", "empowered canola seed", {name: "item_misc_empowered_canola_seed", meta: 0}, {stack: 64});
Item.createItem("item_misc_ender_star", "ender star", {name: "item_misc_ender_star", meta: 0}, {stack: 64});
Item.createItem("item_misc_knife_blade", "knife blade", {name: "item_misc_knife_blade", meta: 0}, {stack: 64});
Item.createItem("item_misc_knife_handle", "knife handle", {name: "item_misc_knife_handle", meta: 0}, {stack: 64});
Item.createItem("item_misc_lens", "lens", {name: "item_misc_lens", meta: 0}, {stack: 64});
Item.createItem("item_misc_mashed_food", "mashed food", {name: "item_misc_mashed_food", meta: 0}, {stack: 64});
Item.createItem("item_misc_paper_cone", "paper cone", {name: "item_misc_paper_cone", meta: 0}, {stack: 64});
Item.createItem("item_misc_rice_dough", "rice dough", {name: "item_misc_rice_dough", meta: 0}, {stack: 64});
Item.createItem("item_misc_rice_slime", "rice slime", {name: "item_misc_rice_slime", meta: 0}, {stack: 64});
Item.createItem("item_misc_ring", "ring", {name: "item_misc_ring", meta: 0}, {stack: 64});
Item.createItem("item_misc_spawner_shard", "spawner shard", {name: "item_misc_spawner_shard", meta: 0}, {stack: 64});
Item.createItem("item_misc_tiny_charcoal", "tiny charcoal", {name: "item_misc_tiny_charcoal", meta: 0}, {stack: 64});
Item.createItem("item_misc_tiny_coal", "tiny coal", {name: "item_misc_tiny_coal", meta: 0}, {stack: 64});
Item.createItem("item_misc_youtube_icon", "youtubeIcon", {name: "item_misc_youtube_icon", meta: 0}, {stack: 64});
Item.createItem("item_more_damage_lens", "more damage lens", {name: "item_more_damage_lens", meta: 0}, {stack: 64});
Item.createItem("item_paxel_overlay", "paxel overlay", {name: "item_paxel_overlay", meta: 0}, {stack: 64});
Item.createItem("item_paxel", "paxel", {name: "item_paxel", meta: 0}, {stack: 64});
Item.createItem("item_phantom_connector", "phantom connector", {name: "item_phantom_connector", meta: 0}, {stack: 64});
Item.createItem("item_pickaxe_crystal_black", "pickaxe crystal black", {name: "item_pickaxe_crystal_black", meta: 0}, {stack: 64});
Item.createItem("item_pickaxe_crystal_blue", "pickaxe crystal blue", {name: "item_pickaxe_crystal_blue", meta: 0}, {stack: 64});
Item.createItem("item_pickaxe_crystal_green", "pickaxe crystal green", {name: "item_pickaxe_crystal_green", meta: 0}, {stack: 64});
Item.createItem("item_pickaxe_crystal_light_blue", "pickaxe crystal light blue", {name: "item_pickaxe_crystal_light_blue", meta: 0}, {stack: 64});
Item.createItem("item_pickaxe_crystal_red", "pickaxe crystal red", {name: "item_pickaxe_crystal_red", meta: 0}, {stack: 64});
Item.createItem("item_pickaxe_crystal_white", "pickaxe crystal white", {name: "item_pickaxe_crystal_white", meta: 0}, {stack: 64});
Item.createItem("item_pickaxe_emerald", "pickaxe emerald", {name: "item_pickaxe_emerald", meta: 0}, {stack: 64});
Item.createItem("item_pickaxe_light", "pickaxe light", {name: "item_pickaxe_light", meta: 0}, {stack: 64});
Item.createItem("item_pickaxe_obsidian", "pickaxe obsidian", {name: "item_pickaxe_obsidian", meta: 0}, {stack: 64});
Item.createItem("item_pickaxe_quartz", "pickaxe quartz", {name: "item_pickaxe_quartz", meta: 0}, {stack: 64});
Item.createItem("item_player_probe", "player probe", {name: "item_player_probe", meta: 0}, {stack: 64});
Item.createItem("item_potion_ring_advanced", "potion ring advanced", {name: "item_potion_ring_advanced", meta: 0}, {stack: 64});
Item.createItem("item_potion_ring", "potion ring", {name: "item_potion_ring", meta: 0}, {stack: 64});
Item.createItem("item_rarmor_module_reconstructor", "rarmor module reconstructor", {name: "item_rarmor_module_reconstructor", meta: 0}, {stack: 64});
Item.createItem("item_resonant_rice", "resonant rice", {name: "item_resonant_rice", meta: 0}, {stack: 64});
Item.createItem("item_rice_seed", "rice seed", {name: "item_rice_seed", meta: 0}, {stack: 64});
Item.createItem("item_shears_light", "shears light", {name: "item_shears_light", meta: 0}, {stack: 64});
Item.createItem("item_shovel_crystal_black", "shovel crystal black", {name: "item_shovel_crystal_black", meta: 0}, {stack: 64});
Item.createItem("item_shovel_crystal_blue", "shovel crystal blue", {name: "item_shovel_crystal_blue", meta: 0}, {stack: 64});
Item.createItem("item_shovel_crystal_green", "shovel crystal green", {name: "item_shovel_crystal_green", meta: 0}, {stack: 64});
Item.createItem("item_shovel_crystal_light_blue", "shovel crystal light blue", {name: "item_shovel_crystal_light_blue", meta: 0}, {stack: 64});
Item.createItem("item_shovel_crystal_red", "shovel crystal red", {name: "item_shovel_crystal_red", meta: 0}, {stack: 64});
Item.createItem("item_shovel_crystal_white", "shovel crystal white", {name: "item_shovel_crystal_white", meta: 0}, {stack: 64});
Item.createItem("item_shovel_emerald", "shovel emerald", {name: "item_shovel_emerald", meta: 0}, {stack: 64});
Item.createItem("item_shovel_light", "shovel light", {name: "item_shovel_light", meta: 0}, {stack: 64});
Item.createItem("item_shovel_obsidian", "shovel obsidian", {name: "item_shovel_obsidian", meta: 0}, {stack: 64});
Item.createItem("item_shovel_quartz", "shovel quartz", {name: "item_shovel_quartz", meta: 0}, {stack: 64});
Item.createItem("item_small_to_medium_crate_upgrade", "small to medium crate upgrade", {name: "item_small_to_medium_crate_upgrade", meta: 0}, {stack: 64});
Item.createItem("item_snail", "snail", {name: "item_snail", meta: 0}, {stack: 64});
Item.createItem("item_solidified_experience", "solidified experience", {name: "item_solidified_experience", meta: 0}, {stack: 64});
Item.createItem("item_spawner_changer", "spawner changer", {name: "item_spawner_changer", meta: 0}, {stack: 64});
Item.createItem("item_suction_ring", "suction ring", {name: "item_suction_ring", meta: 0}, {stack: 64});
Item.createItem("item_sword_crystal_black", "sword crystal black", {name: "item_sword_crystal_black", meta: 0}, {stack: 64});
Item.createItem("item_sword_crystal_blue", "sword crystal blue", {name: "item_sword_crystal_blue", meta: 0}, {stack: 64});
Item.createItem("item_sword_crystal_green", "sword crystal green", {name: "item_sword_crystal_green", meta: 0}, {stack: 64});
Item.createItem("item_sword_crystal_light_blue", "sword crystal light blue", {name: "item_sword_crystal_light_blue", meta: 0}, {stack: 64});
Item.createItem("item_sword_crystal_red", "sword crystal red", {name: "item_sword_crystal_red", meta: 0}, {stack: 64});
Item.createItem("item_sword_crystal_white", "sword crystal white", {name: "item_sword_crystal_white", meta: 0}, {stack: 64});
Item.createItem("item_sword_emerald", "sword emerald", {name: "item_sword_emerald", meta: 0}, {stack: 64});
Item.createItem("item_sword_light", "sword light", {name: "item_sword_light", meta: 0}, {stack: 64});
Item.createItem("item_sword_obsidian", "sword obsidian", {name: "item_sword_obsidian", meta: 0}, {stack: 64});
Item.createItem("item_sword_quartz", "sword quartz", {name: "item_sword_quartz", meta: 0}, {stack: 64});
Item.createItem("item_tablet", "tablet", {name: "item_tablet", meta: 0}, {stack: 64});
Item.createItem("item_tele_staff", "tele staff", {name: "item_tele_staff", meta: 0}, {stack: 64});
Item.createItem("item_upgrade_speed", "upgrade speed", {name: "item_upgrade_speed", meta: 0}, {stack: 64});
Item.createItem("item_void_bag", "void bag", {name: "item_void_bag", meta: 0}, {stack: 64});
Item.createItem("item_water_bowl", "water bowl", {name: "item_water_bowl", meta: 0}, {stack: 64});
Item.createItem("item_water_removal_ring", "water removal ring", {name: "item_water_removal_ring", meta: 0}, {stack: 64});
Item.createItem("item_wings_of_the_bats", "wings of the bats", {name: "item_wings_of_the_bats", meta: 0}, {stack: 64});
Item.createItem("item_worm", "worm", {name: "item_worm", meta: 0}, {stack: 64});
